### ISSUE TITLE
VariableStiffnesselasticity.py的运行问题解决

### ISSUE THREAD

**Issue by ximalayakeng** [BraveDrXuTF/VOL#1]
在运行VariableStiffnesselasticity.py时，遇到的问题
1.先删除VOLcore中class energyBasedModule中deepdirection后的初始值并改为None
2.删除VariableStiffnesselasticity.py中导入的debug，不然进入ipdb调试

**Comment by BraveDrXuTF** [comment]
该运行问题可以通过以上两个步骤解决。即遇到deepdirection类没有定义直接删除；Import的库如果没有用到直接删除；
